# Usar una imagen base de Node.js
FROM node:18-alpine

# Crear y definir el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el package.json y package-lock.json
COPY package*.json ./

# Instalar las dependencias del proyecto
RUN npm install

# Copiar el resto del código de la aplicación
COPY . .

# Exponer el puerto que utilizará el servidor
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["npm", "start"]